Dlampriadis/masking policy overview
EloiSanchez/snowflake-health-check pull request #40
Opened 2023-07-20 08:40 UTC by DLampriadis

## Summary
Should produce an overview of the masking policies applied to the tables.

## Does this PR refer to any issue?
#22 

## Objects created or modified
### Files
- masking_policy_overview.sql

### Procedure
- masking_policy_overview()

### Tables
- masking_policy_overview_results

## I made sure that...
- [ ] The files are named `{health_check_name}.sql/py`, are saved in the proper directory and are well documented
- [ ] The procedure is named `{health_check_name}` and is stored in the schema `health_checks.public`
- [ ] The tables created are named `{health_check_name}[_extra_info]_[results or intermediate]` and are stored in the schema `health_checks.public`
- [ ] I run the pre-commit hooks in all my commits

## Does my code code need to be tested?
Yes

## The reviewer should check
1. Run procedure
2. Select from created table
3. Give insights on how this would look like or used by the end user. Maybe just the table is not enough

2023-07-21 10:50 UTC, wiesnseb commented on snowflake-health-checks/src/libraries/procedures/masking_policy_overview.sql
> +        from SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES final
why capital amigo?

2023-07-21 10:54 UTC, wiesnseb requested changes
see comment

2023-07-24 08:44 UTC, DLampriadis commented
Done, ready for review

2023-07-24 11:19 UTC, EloiSanchez approved these changes
Fix the typo then it will be fine for merging already.

2023-07-24 11:19 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/procedures/masking_policy_overview.sql
> +        return 'There objects in the account with masking policies applied on them. Have an overview here: health_checks.public.masking_policy_overview_results'
Fix typo here: 'There **are** objects in the account ...'

2023-07-24 14:24 UTC, EloiSanchez approved these changes
Nice

2023-07-25 11:06 UTC, wiesnseb approved these changes
all good now

2023-07-25 11:07 UTC, merged