Dlampriadis/queuing warehouses
EloiSanchez/snowflake-health-check pull request #44
Opened 2023-07-21 15:22 UTC by DLampriadis

## Summary
Checks for warehouses that have experienced queuing.

## Does this PR refer to any issue?
#10 

## Objects created or modified
### Files
- queuing_warehouses.sql

### Procedure
- queuing_warehouses()

### Tables
- queuing_warehouses_overview_results
- get_wh_days() - function
- date_spine

## I made sure that...
- [ ] The files are named `{health_check_name}.sql/py`, are saved in the proper directory and are well documented
- [ ] The procedure is named `{health_check_name}` and is stored in the schema `health_checks.public`
- [ ] The tables created are named `{health_check_name}[_extra_info]_[results or intermediate]` and are stored in the schema `health_checks.public`
- [ ] I run the pre-commit hooks in all my commits

## Does my code code need to be tested?
Yes

## The reviewer should check
1. Run procedure
2. Select from created table

2023-07-24 08:34 UTC, DLampriadis commented
Last commit update:

Files
- queuing_warehouses.py

Parts that need changes:
user input for warehouse name and time period. Now there is interaction only through cl.

2023-07-24 13:56 UTC, EloiSanchez requested changes
Create a single class for this health check and make two different methods that return the different plots, instead of two different classes.

Also, I have left some comments.

2023-07-24 13:56 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/procedures/queuing_warehouses.sql
> +-- needs to have for three years \\\ THIS WILL GO IN THE UTILS FILE
The utils is on main as of #38, so it can be moved now.

2023-07-24 13:56 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/procedures/queuing_warehouses.sql
> +            having total_avg_run_seconds > 0  -- THIS NEEDS TO BE DISCUSSED
I would keep it like this, with the > 0. It gives us the most flexibility and information that we can then filter out or use as we want in Python.

2023-07-24 13:56 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/procedures/queuing_warehouses.sql
> +        create or replace function get_wh_days(wh_name varchar, fromdate date, todate date)
The function works fine but maybe get a more adequate name? Something like `get_wh_load`? It would also be nice if we could send a variable from Python that determines the level of aggregation (5 min, 15 min, 30 min, 60 min?).

2023-07-24 13:56 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/plots/queuing_warehouses.py
> +        self.end_date = str(input("To date, YYYY,MM,DD: "))
Instead of asking for user input, if you want to test it with different values, pass the three variables as warehouse input as we will do once we integrate the plot with streamlit.

Also, take into account that these variables should be passed to the method that creates the plot, not the `__init__` method.

Finally, maybe use `start_date` instead of `strt_date` since we don't shorten that much but it gets hard to read.

2023-07-24 13:56 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/plots/queuing_warehouses.py
> +from snowflake.connector import SnowflakeConnection
There are some unused imports that could be removed.

2023-07-26 09:57 UTC, DLampriadis commented on snowflake-health-checks/src/libraries/procedures/queuing_warehouses.sql
> +        create or replace function get_wh_days(wh_name varchar, fromdate date, todate date)
"It would also be nice if we could send a variable from Python that determines the level of aggregation (5 min, 15 min, 30 min, 60 min?)."
This part can be implemented on a later date, under the same issue.

2023-07-28 09:17 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/results/queuing_warehouses.py
> +        )
Maybe return this sorted already from Snowflake? Avoid as much calculation as possible in Python

2023-07-28 09:20 UTC, EloiSanchez commented on snowflake-health-checks/src/libraries/results/queuing_warehouses.py
> +        )
Also, return from snowflake the time format of the x axis (`AGG_TIME`) as `XX:XX` instead of `XX:XX:XX` since we do not need the seconds in the plot. I think it would be cleaner.

2023-07-28 10:01 UTC, DLampriadis commented on snowflake-health-checks/src/libraries/results/queuing_warehouses.py
> +        )
Done both

2023-07-31 08:47 UTC, DLampriadis commented
Ready to be reviewed. Separated the overview of the warehouses plot to a new issue. Since this is part of the autosuspend plots.

Files that have been updated/changed:

1) check **utils.sql** procedure for date_spine
2) call procedure **queuing_warehouses()**
3) call function: select * FROM TABLE (**get_wh_load**('HEALTH_CHECK_WH',  '2023-07-10', '2023-07-25', 60));
4) streamlit run ..\Home.py -- and check last plot for different date ranges, time aggregations and different warehouses.

2023-07-31 09:29 UTC, wiesnseb commented on snowflake-health-checks/src/libraries/procedures/queuing_warehouses.sql
> +show parameters
can be removed i think

2023-07-31 09:29 UTC, wiesnseb commented on snowflake-health-checks/src/libraries/procedures/queuing_warehouses.sql
> +select *
can be removed i think

2023-07-31 09:33 UTC, wiesnseb requested changes
## Summary
Plot Warehouse Restarts doesn’t show up
- Error: SQL compilation error: Unknown table function AUTO_SUSPEND_HOURLY_RESTARTS_AGG

What i have done:
run utils.py (no issues here)
run auto_suspend.py
 - for query select * from table(hourly_restarts_agg('health_check_wh', '2023-07-20', '2023-07-27'));  —> SQL compilation error: Unknown table function HOURLY_RESTARTS_AGG —> i think this can be removed anyway.
run Home.py
- Plot for Warehouse loads runs fine, also with adjusted parameters
<img width="2560" alt="Bildschirmfoto 2023-07-31 um 11 32 45" src="https://github.com/EloiSanchez/snowflake-health-check/assets/38764832/aa34df8c-1fd6-4999-a323-8fb38e832946">

2023-07-31 11:11 UTC, EloiSanchez approved these changes
Happy coding ☀️

2023-07-31 11:40 UTC, wiesnseb approved these changes
after the fix with the error it should be okay. Run's in empty database.

2023-07-31 11:41 UTC, merged